SGProjects/GroupProject/team-1-codingchamps/CodeChampsAI/CodeChampsAI/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CodeChampsAI.Models
{
    public class LoginViewModel
    {
        [Required]
        [Display(Name = "Username")]
        public string Username { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [Display(Name = "Remember me?")]
        public bool RememberMe { get; set; }

        public bool SignupSuccess { get; set; }
    }
}

SGProjects/GroupProject/team-1-codingchamps/CodeChampsAI/CodeChampsAI/Controllers/LoginController.cs
using CodeChampsAI.Data;
using CodeChampsAI.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace CodeChampsAI.Controllers
{
    public class LoginController : Controller
    {
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        public LoginController()
        {
        }

        public LoginController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }


        // GET: Login/Index
        [HttpGet]
        [AllowAnonymous]
        public ActionResult Index(LoginViewModel model)
        {
            ModelState.Clear();
            return View(model);
        }

        // POST: Login/Index
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Index(LoginViewModel model, string returnUrl)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var user = UserManager.FindByName(model.Username);
            if (user!= null && UserManager.IsInRole(user.Id, "Disabled"))
            {
                ModelState.AddModelError("", "Account Disabled");
                return View(model);
            }
            // This doesn't count login failures towards account lockout
            // To enable password failures to trigger account lockout, change to shouldLockout: true
            var result = await SignInManager.PasswordSignInAsync(model.Username, model.Password, model.RememberMe, shouldLockout: false);
            switch (result)
            {
                case SignInStatus.Success:
                    return RedirectToLocal(returnUrl);
                case SignInStatus.LockedOut:
                    return View("Lockout");
                case SignInStatus.RequiresVerification:
                    return RedirectToAction("SendCode", new { ReturnUrl = returnUrl, RememberMe = model.RememberMe });
                case SignInStatus.Failure:
                default:
                    ModelState.AddModelError("", "Invalid login attempt.");
                    return View(model);
            }
        }

        // POST: /Account/LogOff
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LogOff()
        {
            AuthenticationManager.SignOut(DefaultAuthenticationTypes.ApplicationCookie);
            return RedirectToAction("Index", "Home");
        }

        private ActionResult RedirectToLocal(string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }
            return RedirectToAction("Index", "Home");
        }

        private IAuthenticationManager AuthenticationManager
        {
            get
            {
                return HttpContext.GetOwinContext().Authentication;
            }
        }
    }
}

SGProjects/GroupProject/team-1-codingchamps/CodeChampsAI/CodeChampsAI/Controllers/SignupController.cs
using CodeChampsAI.Data;
using CodeChampsAI.Models;
using CodeChampsAI.Models.Identity;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace CodeChampsAI.Controllers
{
    public class SignupController : Controller
    {
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        public SignupController()
        {
        }

        public SignupController(ApplicationUserManager userManager, ApplicationSignInManager signinManager)
        {
            UserManager = userManager;
            SignInManager = signinManager;
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }


        // GET: Signup
        [AllowAnonymous]
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Index(RegisterViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            AppUser userToCreate = new AppUser
            {
                UserName = model.UserName,
                FirstName = model.FirstName,
                LastName = model.LastName,
                Email = model.Email
            };

            var createUserResult = UserManager.Create(userToCreate, model.Password);

            if (!createUserResult.Succeeded)
            {
                AddErrors(createUserResult);
                return View(model);
            }

            var addRoleResult = UserManager.AddToRole(userToCreate.Id, "User");

            if (!addRoleResult.Succeeded)
            {
                UserManager.Delete(userToCreate);
                AddErrors(addRoleResult);
                return View(model);
            }

            SignInManager.SignIn(userToCreate, false, false);

            string code = UserManager.GenerateEmailConfirmationToken(userToCreate.Id);
            var callbackUrl = Url.Action("ConfirmEmail", "Account", new { userId = userToCreate.Id, code = code }, protocol: Request.Url.Scheme);
            await UserManager.SendEmailAsync(userToCreate.Id, "Confirm your account", "Please confirm your account by clicking <a href=\"" + callbackUrl + "\">here</a>");

            return RedirectToAction("Index", "Home", new { SignupSuccess = true });
        }

        private void AddErrors(IdentityResult result)
        {
            foreach(var error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }
    }
}

SGProjects/GroupProject/team-1-codingchamps/CodeChampsAI/CodeChampsAI/Views/Login/Index.cshtml
@model CodeChampsAI.Models.LoginViewModel
@{
    ViewBag.Title = "Login";
}

<div class="row">
    <div class="col-xs-offset-2 col-xs-6">
        <section id="loginForm">
            @using (Html.BeginForm("Index", "Login", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                if (Model.SignupSuccess)
                {
                    <p class="text-success">Successfully Signed Up</p>
                }
                <div class="form-group">
                    @Html.LabelFor(m => m.Username, new { @class = "col-lg-2 control-label" })
                    <div class="col-lg-10">
                        @Html.TextBoxFor(m => m.Username, new { @class = "form-control", placeholder = "Username" })
                        @Html.ValidationMessageFor(m => m.Username, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Password, new { @class = "col-lg-2 control-label" })
                    <div class="col-lg-10">
                        @Html.PasswordFor(m => m.Password, new { @class = "form-control", placeholder = "Password" })
                        @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-lg-offset-2 col-lg-10">
                        <div class="checkbox-inline">
                            @Html.CheckBoxFor(m => m.RememberMe, new { @class = "checkbox" })
                            @Html.LabelFor(m => m.RememberMe, new { @class = "" })
                        </div>
                   </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <input type="submit" value="Sign In" class="btn btn-primary" />
                    </div>
                </div>

                <div class="col-sm-offset-2 col-sm-10">
                    <p>Not a member?</p>
                    <p>@Html.ActionLink("Signup for an account!", "Index", "Signup", new { }, new { })</p>
                </div>

                <div class="col-sm-offset-2 col-sm-10">
                    <p>Forgot your password?</p>
                    <p>@Html.ActionLink("Reset password", "ForgotPassword", "Account", new { }, new { })</p>
                </div>
            }
        </section>
    </div>
</div>