SGProjects/GroupProject/team-1-codingchamps/CodeChampsAI/CodeChampsAI/Controllers/LoginController.cs
using CodeChampsAI.Data;
using CodeChampsAI.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace CodeChampsAI.Controllers
{
    public class LoginController : Controller
    {
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        public LoginController()
        {
        }

        public LoginController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }


        // GET: Login/Index
        [HttpGet]
        [AllowAnonymous]
        public ActionResult Index(LoginViewModel model)
        {
            ModelState.Clear();
            return View(model);
        }

        // POST: Login/Index
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Index(LoginViewModel model, string returnUrl)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var user = UserManager.FindByName(model.Username);
            if (user!= null && UserManager.IsInRole(user.Id, "Disabled"))
            {
                ModelState.AddModelError("", "Account Disabled");
                return View(model);
            }
            // This doesn't count login failures towards account lockout
            // To enable password failures to trigger account lockout, change to shouldLockout: true
            var result = await SignInManager.PasswordSignInAsync(model.Username, model.Password, model.RememberMe, shouldLockout: false);
            switch (result)
            {
                case SignInStatus.Success:
                    return RedirectToLocal(returnUrl);
                case SignInStatus.LockedOut:
                    return View("Lockout");
                case SignInStatus.RequiresVerification:
                    return RedirectToAction("SendCode", new { ReturnUrl = returnUrl, RememberMe = model.RememberMe });
                case SignInStatus.Failure:
                default:
                    ModelState.AddModelError("", "Invalid login attempt.");
                    return View(model);
            }
        }

        // POST: /Account/LogOff
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LogOff()
        {
            AuthenticationManager.SignOut(DefaultAuthenticationTypes.ApplicationCookie);
            return RedirectToAction("Index", "Home");
        }

        private ActionResult RedirectToLocal(string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }
            return RedirectToAction("Index", "Home");
        }

        private IAuthenticationManager AuthenticationManager
        {
            get
            {
                return HttpContext.GetOwinContext().Authentication;
            }
        }
    }
}

SGProjects/GroupProject/team-1-codingchamps/CodeChampsAI/CodeChampsAI/Controllers/StaticController.cs
using CodeChampsAI.Data;
using Ninject;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CodeChampsAI.Controllers
{
    public class StaticController : Controller
    {
        // GET: Static
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult View(int id)
        {
            var repo = DIContainer.Kernel.Get<IRepository>();
            var model = repo.GetStaticPageById(id);
            return View(model);
        }
    }
}

SGProjects/GroupProject/team-1-codingchamps/CodeChampsAI/CodeChampsAI/Views/Shared/_Dashboard.cshtml
@using Microsoft.AspNet.Identity
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - AI Blog</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="container">
        @using (Html.BeginForm("LogOff", "Login", FormMethod.Post, new { id = "logoutForm" }))
        {
            @Html.AntiForgeryToken()
        }
        <p class="text-left">
            @Html.ActionLink("AI Blog", "Index", "Home", new { }, new { })
            <span style="float: right">
                @if (Request.IsAuthenticated)
                {<a href="javascript:document.getElementById('logoutForm').submit()">Log off</a> }
                else
                { @Html.ActionLink("Sign-in/Register", "Index", "Login", new { }, new { })}
            </span>
        </p>

        <div class="container navbar navbar-default">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Posts", "PostView", "Admin", new { }, new { })</li>
                        <li>@Html.ActionLink("New Post", "NewPost", "Admin", new { }, new { })</li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li>@Html.ActionLink("Pages", "Pages", "Admin", new {  }, new { })</li>
                            <li>@Html.ActionLink("New Page", "NewPage", "Admin", new {  }, new { })</li>
                        }
                        <li>@Html.ActionLink("Posts to Approve", "Approval", "Admin", new {  }, new { })</li>
                        <li>@Html.ActionLink("Rejected Posts", "Rejected", "Admin", new {  }, new { })</li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li>@Html.ActionLink("Users", "Users", "Admin", new { }, new { })</li>
                        }
                        <li>@Html.ActionLink("Change Password", "ChangePassword", "Admin", new { }, new { })</li>
                    </ul>
                </div>
            </div>
        </div>

        <!--Body of page-->
        <div class="">
            @RenderBody()
        </div>
    </div>

    <div class="container">
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - AI Blog Space</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/Site.js"></script>
</body>
</html>

SGProjects/GroupProject/team-1-codingchamps/CodeChampsAI/CodeChampsAI/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - AI Blog</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="container">
        @using (Html.BeginForm("LogOff", "Login", FormMethod.Post, new { id = "logoutForm" }))
            {
            @Html.AntiForgeryToken()
        }
        <p class="text-right">


            @if (Request.IsAuthenticated)
            {
                if (User.IsInRole("User"))
                {<a href="javascript:document.getElementById('logoutForm').submit()">Log off</a>}
                else
                {@Html.ActionLink("Dashboard", "PostView", "Admin", new { }, new { })}
            }
            else
            { @Html.ActionLink("Sign-in/Register", "Index", "Login", new { }, new { })}
        </p>

        <div class="jumbotron">
            <h1>Bacon Blog</h1>
            <p>Formerly: AI Blog Space</p>
        </div>

        <!--Nav Bar-->
        @{
            Html.RenderAction("Sidebar", "Home", new { });
        }

        <!--Body of page-->
        <div class="col-xs-9">
            @RenderBody()
        </div>
    </div>

    <div class="container">
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - AI Blog Space</p>
        </footer>
    </div>
    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>

</body>
</html>

SGProjects/GroupProject/team-1-codingchamps/CodeChampsAI/CodeChampsAI/Views/Shared/_Sidebar.cshtml
@model List<CodeChampsAI.Models.StaticPage>

<div class="navbar navbar-default col-sm-3 col-lg-2">
    <div class="">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("AI Blog", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Posts", "Index", "Posts", new { }, new { })</li>
                <li>
                    @using (Html.BeginForm("Search", "Posts", FormMethod.Get, new { }))
                    {
                        @Html.TextBox("searchTerm", null, new { @class = "form-control" })
                        <br />
                                <button type="submit" class="btn btn-primary form-control">Search</button>
                    }
                </li>
                @foreach (var item in Model)
                {
                    <li>@Html.ActionLink(item.LinkName, "View", "Static", new { id = item.StaticPageId }, new { })</li>
                }

            </ul>

        </div>
    </div>
</div>